//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medias
    {
        public int Id { get; set; }
        public string NamePhoto { get; set; }
        public string Date { get; set; }
        public string Path { get; set; }
        public string IsDeleted { get; set; }
        public int ZonesId { get; set; }
        public int PeopleGroupsId { get; set; }
        public int EventsId { get; set; }
    
        public virtual Zones Zone { get; set; }
        public virtual PeopleGroups PeopleGroup { get; set; }
        public virtual Events Event { get; set; }
    }
}
